name: Post Submit
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: read

jobs:
  push_to_registry:
    name: Build and push images to quay.io/medik8s
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with: 
          go-version-file: 'go.mod' 
          cache-dependency-path: 'go.sum' 

      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build and push CSV 0.0.1 + latest images, for pushes
        if: ${{ github.ref_type != 'tag' }}
        run: make bundle container-build container-push

      - name: Build and push versioned based on tag
        if: ${{ github.ref_type == 'tag' }}
        # remove leading 'v' from tag!
        run: export VERSION=$(echo $GITHUB_REF_NAME | sed 's/v//') && make bundle container-build container-push

      - name: Create release with manifests
        if: ${{ github.ref_type == 'tag' }}
        # https://github.com/marketplace/actions/github-release-create-update-and-upload-assets
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          body: |
            # Machine Deletion Remediation operator ${{ github.ref_name }}
            
            ## Notable Changes
            
            * TODO

            ## Release Artifacts
            
            ### Images

            * Operator: quay.io/medik8s/machine-deletion-remediation-operator:${{ github.ref_name }}
            * Bundle: quay.io/medik8s/machine-deletion-remediation-operator-bundle:${{ github.ref_name }}
            
            ### Source code and OLM manifests

            Please find the source code and the OLM manifests in the `Assets` section below.

          gzip: folders
          files: >
            Manifests:bundle/


